// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: main.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0}
}

func (x *DataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SmallNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           int32                  `protobuf:"varint,1,opt,name=one,proto3" json:"one,omitempty"`      // Используем int32 вместо int8
	Two           int32                  `protobuf:"varint,2,opt,name=two,proto3" json:"two,omitempty"`      // Используем int32 вместо int
	Three         float32                `protobuf:"fixed32,3,opt,name=three,proto3" json:"three,omitempty"` // Используем float вместо float32
	Four          float64                `protobuf:"fixed64,4,opt,name=four,proto3" json:"four,omitempty"`   // Используем double вместо float64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmallNumber) Reset() {
	*x = SmallNumber{}
	mi := &file_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmallNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmallNumber) ProtoMessage() {}

func (x *SmallNumber) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmallNumber.ProtoReflect.Descriptor instead.
func (*SmallNumber) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{1}
}

func (x *SmallNumber) GetOne() int32 {
	if x != nil {
		return x.One
	}
	return 0
}

func (x *SmallNumber) GetTwo() int32 {
	if x != nil {
		return x.Two
	}
	return 0
}

func (x *SmallNumber) GetThree() float32 {
	if x != nil {
		return x.Three
	}
	return 0
}

func (x *SmallNumber) GetFour() float64 {
	if x != nil {
		return x.Four
	}
	return 0
}

type SmallString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           string                 `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two           string                 `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	Three         string                 `protobuf:"bytes,3,opt,name=three,proto3" json:"three,omitempty"`
	Four          string                 `protobuf:"bytes,4,opt,name=four,proto3" json:"four,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmallString) Reset() {
	*x = SmallString{}
	mi := &file_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmallString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmallString) ProtoMessage() {}

func (x *SmallString) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmallString.ProtoReflect.Descriptor instead.
func (*SmallString) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{2}
}

func (x *SmallString) GetOne() string {
	if x != nil {
		return x.One
	}
	return ""
}

func (x *SmallString) GetTwo() string {
	if x != nil {
		return x.Two
	}
	return ""
}

func (x *SmallString) GetThree() string {
	if x != nil {
		return x.Three
	}
	return ""
}

func (x *SmallString) GetFour() string {
	if x != nil {
		return x.Four
	}
	return ""
}

type SmallMixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           int32                  `protobuf:"varint,1,opt,name=one,proto3" json:"one,omitempty"` // Используем int32 вместо int
	Two           string                 `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	Three         bool                   `protobuf:"varint,3,opt,name=three,proto3" json:"three,omitempty"`
	Four          []string               `protobuf:"bytes,4,rep,name=four,proto3" json:"four,omitempty"` // Используем repeated для массива строк
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmallMixed) Reset() {
	*x = SmallMixed{}
	mi := &file_main_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmallMixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmallMixed) ProtoMessage() {}

func (x *SmallMixed) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmallMixed.ProtoReflect.Descriptor instead.
func (*SmallMixed) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{3}
}

func (x *SmallMixed) GetOne() int32 {
	if x != nil {
		return x.One
	}
	return 0
}

func (x *SmallMixed) GetTwo() string {
	if x != nil {
		return x.Two
	}
	return ""
}

func (x *SmallMixed) GetThree() bool {
	if x != nil {
		return x.Three
	}
	return false
}

func (x *SmallMixed) GetFour() []string {
	if x != nil {
		return x.Four
	}
	return nil
}

type MediumNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           *SmallNumber           `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two           *SmallNumber           `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	Three         *SmallNumber           `protobuf:"bytes,3,opt,name=three,proto3" json:"three,omitempty"`
	Four          *SmallNumber           `protobuf:"bytes,4,opt,name=four,proto3" json:"four,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediumNumber) Reset() {
	*x = MediumNumber{}
	mi := &file_main_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediumNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediumNumber) ProtoMessage() {}

func (x *MediumNumber) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediumNumber.ProtoReflect.Descriptor instead.
func (*MediumNumber) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{4}
}

func (x *MediumNumber) GetOne() *SmallNumber {
	if x != nil {
		return x.One
	}
	return nil
}

func (x *MediumNumber) GetTwo() *SmallNumber {
	if x != nil {
		return x.Two
	}
	return nil
}

func (x *MediumNumber) GetThree() *SmallNumber {
	if x != nil {
		return x.Three
	}
	return nil
}

func (x *MediumNumber) GetFour() *SmallNumber {
	if x != nil {
		return x.Four
	}
	return nil
}

type MediumString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           *SmallString           `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two           *SmallString           `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	Three         *SmallString           `protobuf:"bytes,3,opt,name=three,proto3" json:"three,omitempty"`
	Four          *SmallString           `protobuf:"bytes,4,opt,name=four,proto3" json:"four,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediumString) Reset() {
	*x = MediumString{}
	mi := &file_main_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediumString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediumString) ProtoMessage() {}

func (x *MediumString) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediumString.ProtoReflect.Descriptor instead.
func (*MediumString) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{5}
}

func (x *MediumString) GetOne() *SmallString {
	if x != nil {
		return x.One
	}
	return nil
}

func (x *MediumString) GetTwo() *SmallString {
	if x != nil {
		return x.Two
	}
	return nil
}

func (x *MediumString) GetThree() *SmallString {
	if x != nil {
		return x.Three
	}
	return nil
}

func (x *MediumString) GetFour() *SmallString {
	if x != nil {
		return x.Four
	}
	return nil
}

type MediumMixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           *SmallMixed            `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two           *SmallMixed            `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	Three         *SmallMixed            `protobuf:"bytes,3,opt,name=three,proto3" json:"three,omitempty"`
	Four          *SmallMixed            `protobuf:"bytes,4,opt,name=four,proto3" json:"four,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediumMixed) Reset() {
	*x = MediumMixed{}
	mi := &file_main_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediumMixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediumMixed) ProtoMessage() {}

func (x *MediumMixed) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediumMixed.ProtoReflect.Descriptor instead.
func (*MediumMixed) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{6}
}

func (x *MediumMixed) GetOne() *SmallMixed {
	if x != nil {
		return x.One
	}
	return nil
}

func (x *MediumMixed) GetTwo() *SmallMixed {
	if x != nil {
		return x.Two
	}
	return nil
}

func (x *MediumMixed) GetThree() *SmallMixed {
	if x != nil {
		return x.Three
	}
	return nil
}

func (x *MediumMixed) GetFour() *SmallMixed {
	if x != nil {
		return x.Four
	}
	return nil
}

type LargeNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           *MediumNumber          `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two           *MediumNumber          `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	Three         *MediumNumber          `protobuf:"bytes,3,opt,name=three,proto3" json:"three,omitempty"`
	Four          *MediumNumber          `protobuf:"bytes,4,opt,name=four,proto3" json:"four,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LargeNumber) Reset() {
	*x = LargeNumber{}
	mi := &file_main_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargeNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeNumber) ProtoMessage() {}

func (x *LargeNumber) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeNumber.ProtoReflect.Descriptor instead.
func (*LargeNumber) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{7}
}

func (x *LargeNumber) GetOne() *MediumNumber {
	if x != nil {
		return x.One
	}
	return nil
}

func (x *LargeNumber) GetTwo() *MediumNumber {
	if x != nil {
		return x.Two
	}
	return nil
}

func (x *LargeNumber) GetThree() *MediumNumber {
	if x != nil {
		return x.Three
	}
	return nil
}

func (x *LargeNumber) GetFour() *MediumNumber {
	if x != nil {
		return x.Four
	}
	return nil
}

type LargeString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           *MediumString          `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two           *MediumString          `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	Three         *MediumString          `protobuf:"bytes,3,opt,name=three,proto3" json:"three,omitempty"`
	Four          *MediumString          `protobuf:"bytes,4,opt,name=four,proto3" json:"four,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LargeString) Reset() {
	*x = LargeString{}
	mi := &file_main_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargeString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeString) ProtoMessage() {}

func (x *LargeString) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeString.ProtoReflect.Descriptor instead.
func (*LargeString) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{8}
}

func (x *LargeString) GetOne() *MediumString {
	if x != nil {
		return x.One
	}
	return nil
}

func (x *LargeString) GetTwo() *MediumString {
	if x != nil {
		return x.Two
	}
	return nil
}

func (x *LargeString) GetThree() *MediumString {
	if x != nil {
		return x.Three
	}
	return nil
}

func (x *LargeString) GetFour() *MediumString {
	if x != nil {
		return x.Four
	}
	return nil
}

type LargeMixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           *MediumMixed           `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two           *MediumMixed           `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	Three         *MediumMixed           `protobuf:"bytes,3,opt,name=three,proto3" json:"three,omitempty"`
	Four          *MediumMixed           `protobuf:"bytes,4,opt,name=four,proto3" json:"four,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LargeMixed) Reset() {
	*x = LargeMixed{}
	mi := &file_main_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargeMixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeMixed) ProtoMessage() {}

func (x *LargeMixed) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeMixed.ProtoReflect.Descriptor instead.
func (*LargeMixed) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{9}
}

func (x *LargeMixed) GetOne() *MediumMixed {
	if x != nil {
		return x.One
	}
	return nil
}

func (x *LargeMixed) GetTwo() *MediumMixed {
	if x != nil {
		return x.Two
	}
	return nil
}

func (x *LargeMixed) GetThree() *MediumMixed {
	if x != nil {
		return x.Three
	}
	return nil
}

func (x *LargeMixed) GetFour() *MediumMixed {
	if x != nil {
		return x.Four
	}
	return nil
}

var File_main_proto protoreflect.FileDescriptor

const file_main_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"main.proto\x12\x04grpc\"(\n" +
	"\fDataResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"[\n" +
	"\vSmallNumber\x12\x10\n" +
	"\x03one\x18\x01 \x01(\x05R\x03one\x12\x10\n" +
	"\x03two\x18\x02 \x01(\x05R\x03two\x12\x14\n" +
	"\x05three\x18\x03 \x01(\x02R\x05three\x12\x12\n" +
	"\x04four\x18\x04 \x01(\x01R\x04four\"[\n" +
	"\vSmallString\x12\x10\n" +
	"\x03one\x18\x01 \x01(\tR\x03one\x12\x10\n" +
	"\x03two\x18\x02 \x01(\tR\x03two\x12\x14\n" +
	"\x05three\x18\x03 \x01(\tR\x05three\x12\x12\n" +
	"\x04four\x18\x04 \x01(\tR\x04four\"Z\n" +
	"\n" +
	"SmallMixed\x12\x10\n" +
	"\x03one\x18\x01 \x01(\x05R\x03one\x12\x10\n" +
	"\x03two\x18\x02 \x01(\tR\x03two\x12\x14\n" +
	"\x05three\x18\x03 \x01(\bR\x05three\x12\x12\n" +
	"\x04four\x18\x04 \x03(\tR\x04four\"\xa8\x01\n" +
	"\fMediumNumber\x12#\n" +
	"\x03one\x18\x01 \x01(\v2\x11.grpc.SmallNumberR\x03one\x12#\n" +
	"\x03two\x18\x02 \x01(\v2\x11.grpc.SmallNumberR\x03two\x12'\n" +
	"\x05three\x18\x03 \x01(\v2\x11.grpc.SmallNumberR\x05three\x12%\n" +
	"\x04four\x18\x04 \x01(\v2\x11.grpc.SmallNumberR\x04four\"\xa8\x01\n" +
	"\fMediumString\x12#\n" +
	"\x03one\x18\x01 \x01(\v2\x11.grpc.SmallStringR\x03one\x12#\n" +
	"\x03two\x18\x02 \x01(\v2\x11.grpc.SmallStringR\x03two\x12'\n" +
	"\x05three\x18\x03 \x01(\v2\x11.grpc.SmallStringR\x05three\x12%\n" +
	"\x04four\x18\x04 \x01(\v2\x11.grpc.SmallStringR\x04four\"\xa3\x01\n" +
	"\vMediumMixed\x12\"\n" +
	"\x03one\x18\x01 \x01(\v2\x10.grpc.SmallMixedR\x03one\x12\"\n" +
	"\x03two\x18\x02 \x01(\v2\x10.grpc.SmallMixedR\x03two\x12&\n" +
	"\x05three\x18\x03 \x01(\v2\x10.grpc.SmallMixedR\x05three\x12$\n" +
	"\x04four\x18\x04 \x01(\v2\x10.grpc.SmallMixedR\x04four\"\xab\x01\n" +
	"\vLargeNumber\x12$\n" +
	"\x03one\x18\x01 \x01(\v2\x12.grpc.MediumNumberR\x03one\x12$\n" +
	"\x03two\x18\x02 \x01(\v2\x12.grpc.MediumNumberR\x03two\x12(\n" +
	"\x05three\x18\x03 \x01(\v2\x12.grpc.MediumNumberR\x05three\x12&\n" +
	"\x04four\x18\x04 \x01(\v2\x12.grpc.MediumNumberR\x04four\"\xab\x01\n" +
	"\vLargeString\x12$\n" +
	"\x03one\x18\x01 \x01(\v2\x12.grpc.MediumStringR\x03one\x12$\n" +
	"\x03two\x18\x02 \x01(\v2\x12.grpc.MediumStringR\x03two\x12(\n" +
	"\x05three\x18\x03 \x01(\v2\x12.grpc.MediumStringR\x05three\x12&\n" +
	"\x04four\x18\x04 \x01(\v2\x12.grpc.MediumStringR\x04four\"\xa6\x01\n" +
	"\n" +
	"LargeMixed\x12#\n" +
	"\x03one\x18\x01 \x01(\v2\x11.grpc.MediumMixedR\x03one\x12#\n" +
	"\x03two\x18\x02 \x01(\v2\x11.grpc.MediumMixedR\x03two\x12'\n" +
	"\x05three\x18\x03 \x01(\v2\x11.grpc.MediumMixedR\x05three\x12%\n" +
	"\x04four\x18\x04 \x01(\v2\x11.grpc.MediumMixedR\x04four2A\n" +
	"\rSenderService\x120\n" +
	"\bSendData\x12\x10.grpc.LargeMixed\x1a\x12.grpc.DataResponse2F\n" +
	"\x0fReceiverService\x123\n" +
	"\vReceiveData\x12\x10.grpc.LargeMixed\x1a\x12.grpc.DataResponseB\bZ\x06./grpcb\x06proto3"

var (
	file_main_proto_rawDescOnce sync.Once
	file_main_proto_rawDescData []byte
)

func file_main_proto_rawDescGZIP() []byte {
	file_main_proto_rawDescOnce.Do(func() {
		file_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)))
	})
	return file_main_proto_rawDescData
}

var file_main_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_main_proto_goTypes = []any{
	(*DataResponse)(nil), // 0: grpc.DataResponse
	(*SmallNumber)(nil),  // 1: grpc.SmallNumber
	(*SmallString)(nil),  // 2: grpc.SmallString
	(*SmallMixed)(nil),   // 3: grpc.SmallMixed
	(*MediumNumber)(nil), // 4: grpc.MediumNumber
	(*MediumString)(nil), // 5: grpc.MediumString
	(*MediumMixed)(nil),  // 6: grpc.MediumMixed
	(*LargeNumber)(nil),  // 7: grpc.LargeNumber
	(*LargeString)(nil),  // 8: grpc.LargeString
	(*LargeMixed)(nil),   // 9: grpc.LargeMixed
}
var file_main_proto_depIdxs = []int32{
	1,  // 0: grpc.MediumNumber.one:type_name -> grpc.SmallNumber
	1,  // 1: grpc.MediumNumber.two:type_name -> grpc.SmallNumber
	1,  // 2: grpc.MediumNumber.three:type_name -> grpc.SmallNumber
	1,  // 3: grpc.MediumNumber.four:type_name -> grpc.SmallNumber
	2,  // 4: grpc.MediumString.one:type_name -> grpc.SmallString
	2,  // 5: grpc.MediumString.two:type_name -> grpc.SmallString
	2,  // 6: grpc.MediumString.three:type_name -> grpc.SmallString
	2,  // 7: grpc.MediumString.four:type_name -> grpc.SmallString
	3,  // 8: grpc.MediumMixed.one:type_name -> grpc.SmallMixed
	3,  // 9: grpc.MediumMixed.two:type_name -> grpc.SmallMixed
	3,  // 10: grpc.MediumMixed.three:type_name -> grpc.SmallMixed
	3,  // 11: grpc.MediumMixed.four:type_name -> grpc.SmallMixed
	4,  // 12: grpc.LargeNumber.one:type_name -> grpc.MediumNumber
	4,  // 13: grpc.LargeNumber.two:type_name -> grpc.MediumNumber
	4,  // 14: grpc.LargeNumber.three:type_name -> grpc.MediumNumber
	4,  // 15: grpc.LargeNumber.four:type_name -> grpc.MediumNumber
	5,  // 16: grpc.LargeString.one:type_name -> grpc.MediumString
	5,  // 17: grpc.LargeString.two:type_name -> grpc.MediumString
	5,  // 18: grpc.LargeString.three:type_name -> grpc.MediumString
	5,  // 19: grpc.LargeString.four:type_name -> grpc.MediumString
	6,  // 20: grpc.LargeMixed.one:type_name -> grpc.MediumMixed
	6,  // 21: grpc.LargeMixed.two:type_name -> grpc.MediumMixed
	6,  // 22: grpc.LargeMixed.three:type_name -> grpc.MediumMixed
	6,  // 23: grpc.LargeMixed.four:type_name -> grpc.MediumMixed
	9,  // 24: grpc.SenderService.SendData:input_type -> grpc.LargeMixed
	9,  // 25: grpc.ReceiverService.ReceiveData:input_type -> grpc.LargeMixed
	0,  // 26: grpc.SenderService.SendData:output_type -> grpc.DataResponse
	0,  // 27: grpc.ReceiverService.ReceiveData:output_type -> grpc.DataResponse
	26, // [26:28] is the sub-list for method output_type
	24, // [24:26] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_main_proto_init() }
func file_main_proto_init() {
	if File_main_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_main_proto_goTypes,
		DependencyIndexes: file_main_proto_depIdxs,
		MessageInfos:      file_main_proto_msgTypes,
	}.Build()
	File_main_proto = out.File
	file_main_proto_goTypes = nil
	file_main_proto_depIdxs = nil
}
