#!/bin/sh

curl -X POST http://127.0.0.1:3000/$1 \
    -H "Content-Type: application/json" \
    -d '{"id": "90"}'

# # Начало измерения времени в миллисекундах
# start_time=$(($(date +%s) * 1000 + $(date +%N)/1000000))

# for item in {1..$2}; do
#   curl -X POST http://127.0.0.1:3000/$1 \
#     -H "Content-Type: application/json" \
#     -d '{"id": "90"}'
# done;

# # Конец измерения времени в миллисекундах
# end_time=$(($(date +%s) * 1000 + $(date +%N)/1000000))

# # Вычисление общего времени в миллисекундах
# total_time=$((end_time - start_time))

# echo "Общее время выполнения: $total_time миллисекунд"